export const OREDR_CREATE_REQUEST = 'OREDR_CREATE_REQUEST';
export const OREDR_CREATE_SUCCESS = 'OREDR_CREATE_SUCCESS';
export const OREDR_CREATE_FAIL = 'OREDR_CREATE_FAIL';
export const OREDR_CREATE_RESET = 'OREDR_CREATE_RESET';

export const OREDR_DETAILS_REQUEST = 'OREDR_DETAILS_REQUEST';
export const OREDR_DETAILS_SUCCESS = 'OREDR_DETAILS_SUCCESS';
export const OREDR_DETAILS_FAIL = 'OREDR_DETAILS_FAIL';
