export const OREDR_CREATE_REQUEST = 'OREDR_CREATE_REQUEST';
export const OREDR_CREATE_SUCCESS = 'OREDR_CREATE_SUCCESS';
export const OREDR_CREATE_FAIL = 'OREDR_CREATE_FAIL';
export const OREDR_CREATE_RESET = 'OREDR_CREATE_RESET';

export const OREDR_DETAILS_REQUEST = 'OREDR_DETAILS_REQUEST';
export const OREDR_DETAILS_SUCCESS = 'OREDR_DETAILS_SUCCESS';
export const OREDR_DETAILS_FAIL = 'OREDR_DETAILS_FAIL';
export const OREDR_DETAILS_RESET = 'OREDR_DETAILS_RESET';

export const OREDR_PAY_REQUEST = 'OREDR_PAY_REQUEST';
export const OREDR_PAY_SUCCESS = 'OREDR_PAY_SUCCESS';
export const OREDR_PAY_FAIL = 'OREDR_PAY_FAIL';
export const OREDR_PAY_RESET = 'OREDR_PAY_RESET';

export const OREDR_MY_LIST_REQUEST = 'OREDR_MY_LIST_REQUEST';
export const OREDR_MY_LIST_SUCCESS = 'OREDR_MY_LIST_SUCCESS';
export const OREDR_MY_LIST_FAIL = 'OREDR_MY_LIST_FAIL';
export const OREDR_MY_LIST_RESET = 'OREDR_MY_LIST_RESET';

export const OREDR_LIST_REQUEST = 'OREDR_LIST_REQUEST';
export const OREDR_LIST_SUCCESS = 'OREDR_LIST_SUCCESS';
export const OREDR_LIST_FAIL = 'OREDR_LIST_FAIL';

export const OREDR_DELIVERY_REQUEST = 'OREDR_DELIVERY_REQUEST';
export const OREDR_DELIVERY_SUCCESS = 'OREDR_DELIVERY_SUCCESS';
export const OREDR_DELIVERY_FAIL = 'OREDR_DELIVERY_FAIL';
export const OREDR_DELIVERY_RESET = 'OREDR_DELIVERY_RESET';
