export const OREDR_CREATE_REQUEST = 'OREDR_CREATE_REQUEST';
export const OREDR_CREATE_SUCCESS = 'OREDR_CREATE_SUCCESS';
export const OREDR_CREATE_FAIL = 'OREDR_CREATE_FAIL';
export const OREDR_CREATE_RESET = 'OREDR_CREATE_RESET';
